### ISSUE TITLE
Cambios de texto

### ISSUE THREAD

**Issue by malweis** [MedinaZS/busca-mascota#3]
- [x]  Cambiar el texto en la seccion 3 del home y eliminar el coming soon

- [x] Texto en seccion 3 del home: Puedes colaborar para que este sitio siga activo y funcionando siempre ----> Puedes colaborar para que el sitio siga mejorando y más personas la conozcan.

- [x] Texto en sección 4 del home: eliminar el coming soon

- [x]  Cambiar el texto de la seccion de publicar a adopcion a otra cosa, ex "Solicitud de adopcion"

- [x]  Borrar sección de cuentas y Claro de la página Colaborar

**Comment by fjpecci19** [comment]
Todo hecho
