### ISSUE TITLE
Orden en formulario de adopciones

### ISSUE THREAD

**Issue by OscarGonzalez97** [MedinaZS/busca-mascota#7]
Ordenar el formulario que no todos los campos ocupen 12 columnas de bootstrap.
Por ejemplo nombre y especie podrían estar en el mismo row.
Descripción si podría quedar asi porque es un campo con más texto.
Edad y sexo pueden ir en una misma row.
País y ciudad en un mismo row.
Fijarse el formulario de publicar reporte es similar.
<img width="1201" alt="image" src="https://github.com/MedinaZS/busca-mascota/assets/36247829/bbad962f-3ad6-4dfd-8404-95d2992fd99a">

**Comment by fjpecci19** [comment]
Terminado
