### ISSUE TITLE
Pagina 404 por defecto

### ISSUE THREAD

**Issue by OscarGonzalez97** [MedinaZS/busca-mascota#8]
Cambiar la pagina 404 por defecto, que esté en español y que tenga una animación CSS como esta: https://codepen.io/ChaserCat/pen/VwwGzwL

<img width="851" alt="image" src="https://github.com/MedinaZS/busca-mascota/assets/36247829/93526179-4ec5-4b90-bbdf-94cbbd93e6ad">

**Comment by EstebanJS7** [comment]
Trabajo realizado!
